spring:
  application:
    name: resume-web-site-backend

logging:
  level:
    root: INFO
    ru.ai.sin: INFO

  file:
    name: logs/app.log

app:
  logging:
    pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
    max-history: 7
    rotation-pattern: "logs/app.%d{yyyy-MM-dd}.gz"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always


swagger:
  title: "Resume API"
  description: "Документация API"
  version: "0.0.1"

  servers:
    - url: "http://localhost:8080"
      description: "Local Dev Server"
    - url: "https://api.example.com"
      description: "Production Server"
